# Generated by Django 6.0.1 on 2026-01-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view book'), ('can_create', 'can create book'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book')]},
        ),
    ]
