# Generated by Django 5.2.7 on 2026-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_author_id_alter_book_id_alter_librarian_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2025),
        ),
    ]
